### ISSUE TITLE
Fell Trees chooses empty cells. [Indev]

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#13] opened 2019-07-09 16:57 UTC
![image](https://user-images.githubusercontent.com/3108850/60908080-b7d33b00-a283-11e9-8952-6b510fdcbf1f.png)

**Comment by rschurade** [comment] 2019-07-09 17:10
Can't reproduce. I can select the fell tree job and select a big area and it only selects trees and creates jobs for them. Have you selected some other job before or pressed any keys?

**Comment by lokkiser** [comment] 2019-07-09 17:15
Remove plants, but i'm not sure.

**Comment by rschurade** [comment] 2019-07-09 17:40
Ok I see something is not right when having another job selected and selecting the fell tree job

**Comment by rschurade** [comment] 2019-07-09 18:01
fixed in 0.6.6.2

**Closed** 2019-07-19 14:11 UTC
