### ISSUE TITLE
Barrels appear when clicking distiller (inconsitency)

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#26] opened 2019-07-21 23:46 UTC
A small inconsistency: when I click the central tile of a distiller, it does not open the workshop tab. Instead, it opens the tile inspector and 2 barrels appear there (the 2 that were used to craft the workshop. Then I have to click the workshop button to open the tab.

I haven't noticed this with any other workshops.

![image](https://user-images.githubusercontent.com/50493006/61598769-18665e80-ac1a-11e9-9d8c-8b8390766a81.png)

**Comment by rschurade** [comment] 2019-07-22 09:25
Confirmed and it's just a visual glitch with the tileinfowindow. It's also only happening for the distillery because that's the only workshop that takes a container for construction.

**Comment by rschurade** [comment] 2019-07-22 10:26
fixed in 0.6.7.2

**Closed by rschurade** 2019-07-22 10:26 UTC

**Comment by Daxtgnomoria** [comment] 2019-07-22 17:54
A similar thing happens when you click the chair on other workshops. 

It does not appear as a thumbnail, but the tile inspection tab opens and show the chair as a building on the floor:

![image](https://user-images.githubusercontent.com/50493006/61653349-fddfc400-acb1-11e9-8360-8ae7b4bfd63f.png)

Don't know if your patch sill also fix this.

**Comment by rschurade** [comment] 2019-07-22 18:01
Showing the chair up there is correct. not opening the workshop window if nothing else is on the tile is not.
