### ISSUE TITLE
Stockpiles not working properly

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#16] opened 2019-07-18 22:10 UTC
Already reporter using in-game uploader, posting it here to help tracking.

I have several stockpiles that simply stop working. I noticed that it happens with stockpiles with storages built on them (did not test on stockpiles w/o storages).

In this save, stockpile named "Carpenter" has 3 boxes built, for a total of 150. It stores only planks. However, after some time, haulers stopped carrying items to this stockpile. I have 22 planks already built (on my sawmill) but they are not being carried to the stock, even when everyone is idle. In the "overview" window, it says there are 128 planks in this stockpile. I counted each items inside each box manually, and the number 128 is correct (50 + 47 + 31). However, in the debug window, the numbers are incorrect - it says that there are 133 planks (50 + 50 + 33).

A similar problem happens with stockpile named "APPLE". It has capacity of 450, the overview says it has 201, but debug window says it has 203. Haulers also stopped carrying apples to this stockpile after some time, and are now idle, with apples lying around to the north of the map.

As an additional problem, when trying to test another stockpile with wheat (sack built), I ordered the sack to be deconstructed (it had a few wheat inside it), and the sack + wheat simply disappeared from the map. Could not reproduce it.

Also, on another stockpile I created to test bugs (already deleted), I had several boxes built there, all my haulers and other gnomes where idle, and the debug screen showed that several spots where reserved for items, even if there was no one carrying items there (this stockpile also stopped working).

**Comment by rschurade** [comment] 2019-07-19 08:47
The reason for the stockpiles to stop accepting item is easy to find again. The containers are full. The stored item list contains a number of item ids which don't exist anymore. So now I need to find a run time situation where an item gets taken from a stockpile, used in a job to get it destroyed but the ID not removed from the stockpile.

The deconstruction bug I'll move to another issue. It's easier to keep track of bugs if there is just one bug per issue here.

**Comment by Daxtgnomoria** [comment] 2019-07-19 09:57
Just some additional input: 

In the example of the "APPLE" stockpile, this one was just created, never got anywhere near full, and stopped working, whereas not more than 10 apples were used from it.

I created the stockpile (3x3), built boxes (9 in total) and only then allowed apples in there. I monitored my haulers and the stockpile and when it reached 201 apples (203 according to debug), of a total of 450, it stopped working.

**Comment by rschurade** [comment] 2019-07-19 10:10
Are these newly build boxes or did you bring them on embark and they had other items in them?

**Comment by Daxtgnomoria** [comment] 2019-07-19 10:19
I only had one box from embark, so they are probably newly built boxes, but they could have had other items in them before. I will try with newly built boxes.

**Comment by rschurade** [comment] 2019-07-19 10:29
Ok I think I found the reason

`// TODO remove from possible container`

**Comment by Daxtgnomoria** [comment] 2019-07-19 10:49
Actually, not all apples were stored. There is something funky going on:

My workshop shows that there are 461 apples on the map available to make wine:

![image](https://user-images.githubusercontent.com/50493006/61528931-f30a0280-aa17-11e9-8cc3-d4cb7970b872.png)

My stockpile shows that there are 461 apples stored there (overview and debug shows the same number):

![image](https://user-images.githubusercontent.com/50493006/61530106-0e2a4180-aa1b-11e9-9493-db754176b85e.png)

However, I can see that there are apples around in the floor, that should count towards the 461 total:

![image](https://user-images.githubusercontent.com/50493006/61530165-3a45c280-aa1b-11e9-9e80-9c04a023420d.png)

Something is not count correctly, and this time no apples are being consumed since the test started.

**Comment by rschurade** [comment] 2019-07-19 10:51
0.6.6.3 is up

**Comment by rschurade** [comment] 2019-07-19 11:02
This is interesting because both numbers should be correct. The number shown in the workshop window comes directly from the central item storage. It list all items with that type and material. The number in the stockpile window is from a count of all items in the stockpile. So your screenshot is not possible. Do you have a save for that situation?

**Comment by Daxtgnomoria** [comment] 2019-07-19 11:44
There you go:

[23.zip](https://github.com/rschurade/Ingnomia/files/3410891/23.zip)

Stockpile is renamed as: APPLE TEST
Apples on the floor are found on: 60, 49, 100 and 74, 70, 100. (in one of them, i cant even click on the floor to see the tile, it goes directly to the apple item)

I just noticed that the apples in the floor are listed as under jobs on the debug screen.

**Comment by rschurade** [comment] 2019-07-19 11:46
That's intended behavior. If there is only one thing on a tile, item, workshop or designation it directly goes to that info window. You can still open the tile info window with shift+click

**Comment by rschurade** [comment] 2019-07-19 12:21
Ok so what we see is correct. The workshop shows 461 items and the stockpile has 461 items. The 3 apples outside the stockpile have (non existing) job ids which makes them unavailable for the brewery. So this is still a case of the item/jobid bug fml

**Comment by Daxtgnomoria** [comment] 2019-07-19 13:05
Is there anything I can do to release them from those jobs using debug?

**Comment by rschurade** [comment] 2019-07-19 13:07
no and not sure i should add, as this is clearly an indicator that something somewhere is wrong, you could edit the save game and set the jobID for these items to 0

**Comment by rschurade** [comment] 2019-07-19 13:10
My problem now is that it's even harder to find than before as this effected only 3 apples out of 464.

**Comment by Daxtgnomoria** [comment] 2019-07-19 14:46
Well, so far things have been working just fine after your last patch! Haven't seen this bug about items on the floor anymore and stockpiles are working as intended. If I see this happening again ill post here.

**Comment by Daxtgnomoria** [comment] 2019-07-19 15:17
Well, I take that back lol. After some time playing and testing, one of my stockpiles stopped working again. This time is the stockpile where cooked food is stored. 

On the overview it says there are 14 breads stored there, the debug says it has 20, and gnome stopped storing bread there:

![image](https://user-images.githubusercontent.com/50493006/61545956-7e978980-aa40-11e9-98cf-6600d815e07d.png)

Perhaps when gnome consuming items by eating/drinking the same problem is happening?

**Comment by rschurade** [comment] 2019-07-19 15:27
Is that a new game or still the same save?

**Comment by rschurade** [comment] 2019-07-19 16:12
I was able to reproduce it with a new game myself.

**Comment by Daxtgnomoria** [comment] 2019-07-19 16:19
Also, I noticed that it happened to stockpiles that were linked, as well as to stockpiles that were not linked to workshops.

**Comment by rschurade** [comment] 2019-07-19 16:19
I believe I got it, at least another instance. 0.6.6.4 incoming.

**Comment by rschurade** [comment] 2019-07-20 17:25
closing this for now, seems to be working

**Comment by Daxtgnomoria** [comment] 2019-07-21 16:53
Found another problem with stockpiles!

I have items in stockpile that are invisible, and appear in the overview, but not on the map (2 boxes and 3 sacks). They are there, but I can only find them by clicking each tile of the stockpile (the one in red square has the sack).

All this boxes and sacks have items inside them.

I've tried deconstructing them and I also tried building storages on other stockpiles, but they were not picked up. I also remember selling 2 boxes to a merchant.

![image](https://user-images.githubusercontent.com/50493006/61594105-a40ec980-abdf-11e9-97ad-a595912193d9.png)

[74.zip](https://github.com/rschurade/Ingnomia/files/3414812/74.zip)

**Comment by rschurade** [comment] 2019-07-21 16:56
eek

**Comment by Daxtgnomoria** [comment] 2019-07-21 17:07
After that I started revisiting my stockpiles, and found that they are not counting correctly again. I just found this one:

![image](https://user-images.githubusercontent.com/50493006/61594291-0e286e00-abe2-11e9-8b73-7c4ffd61aa6a.png)

In the overview there are 49, counting the items inside the box and on free tiles I found 49 also, but in the debug tab I can see 52.

Saving, exiting and reloading fixes the numbers, though.

[76.zip](https://github.com/rschurade/Ingnomia/files/3414830/76.zip)

**Comment by Daxtgnomoria** [comment] 2019-07-23 20:24
Just to add another stance of the bug related to invisible items on stockpiles.

I have a crate showing on stockpile, on tile inspection, but suck crate does not appear on map and cannot be used to construct anything.

![image](https://user-images.githubusercontent.com/50493006/61744806-11615c80-ad90-11e9-8cfe-c88be1f803cc.png)

[20.zip](https://github.com/rschurade/Ingnomia/files/3423941/20.zip)

**Comment by rschurade** [comment] 2019-07-23 20:54
Hmm that crate is somehow constructed but also in the stockpile inventory.

**Comment by Daxtgnomoria** [comment] 2019-07-23 20:58
I just noticed that also! What I remember is that I was trying to build crates there and somehow not all crates were ordered in the carpenter (this also happened on the other time this bug happened). Then i manually built 2 additional crates and after some time that crate appeared there.

**Comment by Daxtgnomoria** [comment] 2019-07-23 21:21
This crate is duplicated. It is also built on tile "73 87 99". The sprite shows there and when I click that tile it opens the stockpile (as if nothing was on that tile).

![image](https://user-images.githubusercontent.com/50493006/61748089-48873c00-ad97-11e9-918f-5a542f2bd43f.png)

**Comment by rschurade** [comment] 2019-07-23 21:31
Now lets try to reproduce this with a new game.

**Comment by Ext3h** [comment] 2020-12-17 15:59
All the listed issues should be resolved by recent patches.

**Closed by Ext3h** 2020-12-17 15:59 UTC
Labels: bug
