### ISSUE TITLE
Game is crashing without warning (discussion on Steam Forums)

### ISSUE THREAD

**Issue by nataklug** [rschurade/Ingnomia#116] opened 2020-12-05 12:47 UTC
Hello Roest! As we were talking on Steam I am attaching all the dumps I have from the crashs:

[Ingnomia.exe.4184.zip](https://github.com/rschurade/Ingnomia/files/5647060/Ingnomia.exe.4184.zip)
[Ingnomia.exe.4536.zip](https://github.com/rschurade/Ingnomia/files/5647061/Ingnomia.exe.4536.zip)
[Ingnomia.exe.9244.zip](https://github.com/rschurade/Ingnomia/files/5647062/Ingnomia.exe.9244.zip)
[Ingnomia.exe.11520.zip](https://github.com/rschurade/Ingnomia/files/5647063/Ingnomia.exe.11520.zip)
[Ingnomia.exe.15200.zip](https://github.com/rschurade/Ingnomia/files/5647066/Ingnomia.exe.15200.zip)

**Comment by Ext3h** [comment] 2020-12-06 17:42
Caused by #55, should be fixed with recent update.

**Comment by nataklug** [comment] 2020-12-07 00:29
Thank you! I will wait for the update. Should I start a new save after the update?

**Comment by Ext3h** [comment] 2020-12-08 15:19
Has this been solved for you?

Should work even without a new world, in your case, even though some sprites may have gotten permanently mixed up in existing savegames.

**Comment by nataklug** [comment] 2020-12-08 16:11
This is working now. After the update I got yesterday I played for more than 1 hour without any crash.

**Closed** 2020-12-08 16:14 UTC
