### ISSUE TITLE
Gnomes mine without pickaxe equipped

### ISSUE THREAD

**Issue by rschurade** [rschurade/Ingnomia#78] opened 2020-08-29 20:20 UTC
Just saw in my streamed game 5 gnomes mining with a total of 2 pickaxes in the world. Couldn't verify it with a new game. Further investigation is needed.

**Comment by Ashtoruin** [comment] 2020-11-11 17:40
This was reproducible on the latest release for both Woodcutting and Mining. My pickaxes and felling axes are sitting untouched at spawn.

It looks like for Felling and Mining Jobs a check is never done to ensure a proper tool is equipped. I've dug around in the code a bit and it seems for every "Mining" and every "Felling" Job we need to add "Job->setRequiredTool(...)"? 

I may poke around with trying to get this building and see what I can figure out.

**Comment by rschurade** [comment] 2020-11-11 17:44
Thanks for confirming. I make it a priority to fix it myself now.

**Comment by Ashtoruin** [comment] 2020-11-11 19:04
Alright, after some further investigation and discussion on Discord I'm unable to reproduce the bug however for future documentation

All Mining/Tree Felling required no tool and you could mine any layers (Which you should be blocked at layer 86?).
It was my first time launching the game after installing it for the first time on my PC and I've been unable to reproduce after closing the game and re-opening it. Even completely removing all game files and re-installing.

**Closed** 2020-11-12 17:31 UTC
